# Dependencies
markdown:            kramdown
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink: /:year/:month/:day/:title.html

# Setup
title:               'DeccanRubyConf 2017'
tagline:             ''
description:         ''
url:                 'http://2017.deccanrubyconf.org'
baseurl:
paginate:            20

# Custom vars
version:             1.0.0

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

assets:
  js_compressor:  uglifier
  css_compressor: sass

sass:
    sass_dir: assets/sass

# Disable this in development, to reduce build time.
# Remember to enable back and run
# jekyll build
# to rebuild site after new changes, before pushing to s3, using s3_website push
gems:
  - jekyll-paginate
